---
language: generic

services:
  - docker

before_script:
  - env | grep -P '^(TRAVIS|CI)' >> .travis.env
  - docker run -d --name postgres -e POSTGRES_PASSWORD=secret -e POSTGRES_DB=test postgres:9.6

script:
  - docker build -t ushi/pj-api .
  - docker run --link postgres --env-file .travis.env ushi/pj-api bundle exec rake
  - docker run ushi/pj-api bundle exec brakeman -i brakeman.ignore -q -z
  - yarn install
  - yarn snyk auth "${SNYK_API_TOKEN}"
  - yarn snyk test --docker ushi/pj-api

before_deploy:
  - if test -n "${TRAVIS_TAG}"; then
      docker tag ushi/pj-api "ushi/pj-api:${TRAVIS_TAG}" &&
        yarn snyk monitor --docker "ushi/pj-api:${TRAVIS_TAG}";
    else
      docker tag ushi/pj-api "ushi/pj-api:latest";
    fi
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

deploy:
  - provider: script
    skip_cleanup: true
    script: docker push "ushi/pj-api:${TRAVIS_TAG}"
    on:
      tags: true

  - provider: script
    skip_cleanup: true
    script: docker push "ushi/pj-api:latest"
    on:
      branch: master
