language: ruby
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
addons:
  postgresql: "9.4"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  - JWT_KEY=74050cdbe796acd46a76cc2bc8545bcf69a73033af003b27e29480812a87a98a DATABASE_URL=postgresql://postgres@localhost/travis_ci_test
