---
services:
  - docker

before_install:
  - docker run -d --name postgres -e POSTGRES_PASSWORD=secret -e POSTGRES_DB=test postgres:9.6

install:
  - docker build -t pj-api .

before_script:
  - env | grep -P '^(TRAVIS|CI)' >> .travis.env

script:
  - docker run --link postgres --env-file .travis.env pj-api bundle exec rake
  - docker run pj-api bundle exec brakeman -i brakeman.ignore -q -z

before_deploy:
  - if test -n "${TRAVIS_TAG}"; then
      docker tag pj-api "ushi/pj-api:${TRAVIS_TAG}";
    else
      docker tag pj-api "ushi/pj-api:latest";
    fi
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

deploy:
  - provider: script
    skip_cleanup: true
    script: docker push "ushi/pj-api:${TRAVIS_TAG}"
    on:
      tags: true

  - provider: script
    skip_cleanup: true
    script: docker push "ushi/pj-api:latest"
    on:
      branch: master
