api:
  build: .
  volumes:
    - .:/pj-api
  ports:
    - "3000:3000"
  links:
    - postgres
    - mailcatcher
  environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=secret
    - SMTP_HOST=mailcatcher
    - SMTP_PORT=1025
    - APP_HOST=http://localhost:9000
    - MAIL_REPLY=pj <pj@reply.localhost.local>
    - MAIL_FROM=pj <noreply@localhost.local>
  command: rails s -b 0.0.0.0

postgres:
  image: postgres:9.5
  volumes:
    - ~/.docker-volumes/pj-api/postgres:/var/lib/postgresql/data
  environment:
    - POSTGRES_PASSWORD=secret

mailcatcher:
  image: ushi/mailcatcher
  ports:
    - "1080:1080"
