version: '2'
services:
  api:
    build: .
    volumes:
      - .:/pj-api
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - SMTP_HOST=maildev
      - SMTP_PORT=25
      - APP_HOST=http://localhost:9000
      - MAIL_REPLY=pj <pj@reply.localhost.local>
      - MAIL_FROM=pj <noreply@localhost.local>

  postgres:
    image: postgres:9.5
    volumes:
      - ~/.docker-volumes/pj-api/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret

  maildev:
    image: djfarrelly/maildev
    ports:
      - '1080:80'
