api:
  build: .
  volumes:
    - .:/pj-api
  ports:
    - "3000:3000"
  links:
    - postgres
    - mailcatcher
  environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=secret
  command: rails s -b 0.0.0.0

postgres:
  image: postgres
  volumes:
    - ~/.docker-volumes/pj-api/postgres:/var/lib/postgresql/data
  environment:
    - POSTGRES_PASSWORD=secret

mailcatcher:
  image: schickling/mailcatcher
  ports:
    - "1080:1080"
